using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;
using DevExpress.XtraGrid.Views.Grid;
using QLXLT_Data.Models;
using DevExpress.XtraGrid;

namespace QuanLyXepLichThi
{
    public partial class ClassForm : DevExpress.XtraEditors.XtraForm
    {
        public ClassForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            // Call the Load method to get the data for the given DbSet from the database.
            //Program.dbContext.Class.Load();
            // This line of code is generated by Data Source Configuration Wizard
            //gridControl1.DataSource = Program.dbContext.Class.Local.ToBindingList();

            ShowData(gridControl1, gridView1, Program.dbContext.Class.ToList());
        }
        public void ShowData(GridControl gridControl, GridView gridView, List<Class> list)
        {
            DataTable dataTable = new DataTable();
            dataTable.Columns.Add("STT");
            dataTable.Columns.Add("Name");
            dataTable.Columns.Add("Code");
            dataTable.Columns.Add("Id");
            dataTable.Columns["STT"].AutoIncrementStep = 1;
            dataTable.Columns["STT"].AutoIncrement = true;
            dataTable.Columns["STT"].AutoIncrementSeed = 1;

            foreach (var item in list)
            {
                dataTable.Rows.Add(null, item.Name, item.ClassCode, item.ClassId);
            }
            gridControl.DataSource = dataTable;
            gridView.Columns["Id"].Visible = false;
            gridView.Columns["STT"].Width = 10;
            gridView.Columns["STT"].AppearanceHeader.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
            gridView.Columns["STT"].AppearanceCell.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Center;
        }

        private void GridView1_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            DataRow row = gridView1.GetDataRow(0);
            GridView view = sender as GridView;
            DataRow dataRow = view.GetDataRow(e.FocusedRowHandle);
            if (dataRow == null) return;
            string classCode = dataRow.ItemArray[2].ToString();
            int idClass = Program.dbContext.Class.FirstOrDefault(x => x.ClassCode == classCode).ClassId;
            gridControl2.DataSource = new BindingList<Student>(Program.dbContext.Student.Where(x => x.ClassId == idClass).ToList());
        }
    }
}