using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;

namespace QuanLyXepLichThi
{
    public partial class RoomForm : DevExpress.XtraEditors.XtraForm
    {
        public RoomForm()
        {
            InitializeComponent();
            //Program.dbContext.Room.Load();
            // This line of code is generated by Data Source Configuration Wizard
            gridControl1.DataSource = Program.dbContext.Room.Local.ToBindingList();
        }
    }
}