using QLXLT_Data;
using QLXLT_Data.Data;
using QLXLT_Data.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;

namespace QuanLyXepLichThi
{
    public partial class TeacherForm : DevExpress.XtraEditors.XtraForm
    {
        XLTContext context = new XLTContext();
        public TeacherForm()
        {
            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            //// Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            //dbContext.Class.Add(new QLXLT_Data.Models.Class() {ClassId = 1, Name = "aaaa", ClassCode = "AA" });
            //dbContext.SaveChanges();
            //Program.dbContext.Teacher.Load();
            gridControl1.DataSource = Program.dbContext.Teacher.Local.ToBindingList();
        }

        private void FormGiangVien_Load(object sender, EventArgs e)
        {
            //List<Room> list = InforRoom.List();
            //Room room = new Room();
            //room = context.Room.Find(1);
        }
    }
}